resources:
- spinnakerservice.yml
# Apply the patches top down order
patchesStrategicMerge:
#- docker-patch.yml  
- azure-kubernetes-patch.yml
  #- config-patch.yml
  #- profiles-patch.yml
  #- files-patch.yml
  #- service-settings-patch.yml
