apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  validation:
    providers:
      kubernetes:
        enabled: true      
  spinnakerConfig:
    config:
      version: 1.26.6   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: azs
        azs:
          storageAccountName: spinnakerstorageacct01
          storageAccountKey: jVPqPYjw7H1LtDxesoEPZD2GFlBWBFYkzUmIj8MgnOjIjfhbusVlYJmbTSHO9T5XKKXvTkNEc+IQxBQdabQIlQ==
          storageContainerName: spinnaker
      features:
        artifacts: true       
        #providers:
        #dockerRegistry:
        # enabled: true
        # accounts:
        # - name: atb-docker-registry
        #   requiredGroupMembership: []
        #   providerVersion: V2
        #   permissions: {}
        #   address: https://index.docker.io
        #   username: agiletrailblazers
        #   password: password1234
        #   email: info@agiletrailblazers.com
        #   cacheIntervalSeconds: 30
        #   clientTimeoutMillis: 60000
        #   cacheThreads: 1
        #   paginateSize: 100
        #   sortTagsByDate: false
        #   trackDigests: false
        #   insecureRegistry: false
        # primaryAccount: atb-docker-registry
        #kubernetes:
        # enabled: true
        #  accounts:
        # - name: azdok8saccount
        #   providerVersion: V2
        #   cacheThreads: 1
        #   kubeconfigFile: encryptedFile:k8s!n:spin-secret!k:config
        #   onlySpinnakerManaged: false
        #   dockerRegistries:
        #   - accountName: atb-docker-registry
        # primaryAccount: azdok8saccount
  # spec.expose - This section defines how Spinnaker should be publicly exposed
  expose:
    type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
    service:
      type: LoadBalancer
