apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  validation:
    providers:
      kubernetes:
        enabled: true      
  spinnakerConfig:
    config:
      version: 1.26.6   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: azs
        azs:
          storageAccountName: spinnakerstorageacct01
          storageAccountKey: jVPqPYjw7H1LtDxesoEPZD2GFlBWBFYkzUmIj8MgnOjIjfhbusVlYJmbTSHO9T5XKKXvTkNEc+IQxBQdabQIlQ==
          storageContainerName: spinnaker
      features:
        artifacts: true       
  # spec.expose - This section defines how Spinnaker should be publicly exposed
  expose:
    type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
    service:
      type: LoadBalancer
